# Generated by Django 5.1.4 on 2025-08-31 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auths', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='apple_id',
            field=models.CharField(blank=True, help_text='Apple account unique identifier', max_length=255, null=True, unique=True, verbose_name='Apple ID'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='auth_provider',
            field=models.CharField(choices=[('email', 'Email'), ('google', 'Google'), ('apple', 'Apple')], default='email', help_text='The provider used for user authentication', max_length=20, verbose_name='Authentication Provider'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='google_id',
            field=models.CharField(blank=True, help_text='Google account unique identifier', max_length=255, null=True, unique=True, verbose_name='Google ID'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_social_account',
            field=models.BooleanField(default=False, help_text='Indicates if this account was created via social authentication', verbose_name='Is Social Account'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='social_id',
            field=models.CharField(blank=True, help_text='Unique ID from social provider (Google ID, Apple ID, etc.)', max_length=255, null=True, verbose_name='Social ID'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='social_profile_picture_url',
            field=models.URLField(blank=True, help_text='Profile picture URL from social provider', null=True, verbose_name='Social Profile Picture URL'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='auth_user_email_ece7f7_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['google_id'], name='auth_user_google__39783d_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['apple_id'], name='auth_user_apple_i_9800b7_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['auth_provider'], name='auth_user_auth_pr_8860e7_idx'),
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='auth_user',
        ),
    ]
